# Generated by Django 5.1.5 on 2025-01-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_mgmt_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('c', 'confirmed')], default='p', max_length=25),
        ),
    ]
