# Generated by Django 5.1.5 on 2025-02-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_mgmt_system', '0002_remove_order_quantity_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
