# Generated by Django 5.1.5 on 2025-01-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_mgmt_system', '0002_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='number',
            new_name='name',
        ),
    ]
